In [57]:
import numpy as np

In [58]:
numlist = [14, 32, 93, 63, 69, 74]

In [59]:
numarray = np.array(numlist)

In [60]:
numarray

array([14, 32, 93, 63, 69, 74])

In [61]:
len(numarray)

6

In [62]:
numarray[0]

14

In [63]:
numarray[4]

69

In [64]:
numarray[1:3]

array([32, 93])

In [65]:
numarray[-1]

74

In [66]:
numarray[2:-1]

array([93, 63, 69])

In [67]:
numarray[::-2]

array([74, 63, 32])

In [68]:
numarray + 12

array([ 26,  44, 105,  75,  81,  86])

In [69]:
numarray - 23

array([-9,  9, 70, 40, 46, 51])

In [70]:
numarray * 5

array([ 70, 160, 465, 315, 345, 370])

In [71]:
numarray[0]*3

42

In [72]:
np.sum(numarray)

345

In [73]:
np.mean(numarray)

57.5

In [74]:
np.max(numarray)

93

In [75]:
numarray_radian = numarray*np.pi/180.0

In [76]:
numarray_radian

array([0.2443461 , 0.55850536, 1.6231562 , 1.09955743, 1.20427718,
       1.29154365])

In [77]:
np.sin(numarray_radian)

array([0.2419219 , 0.52991926, 0.99862953, 0.89100652, 0.93358043,
       0.9612617 ])

In [78]:
np.cos(numarray_radian)

array([ 0.97029573,  0.8480481 , -0.05233596,  0.4539905 ,  0.35836795,
        0.27563736])

In [79]:
np.tan(numarray_radian)

array([  0.249328  ,   0.62486935, -19.08113669,   1.96261051,
         2.60508906,   3.48741444])

In [80]:
np.arcsin(numarray_radian)

/tmp/ipykernel_9564/4216322707.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(numarray_radian)


array([0.24684529, 0.59258285,        nan,        nan,        nan,
              nan])

In [81]:
np.arccos(numarray_radian)

/tmp/ipykernel_9564/520491689.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(numarray_radian)


array([1.32395104, 0.97821348,        nan,        nan,        nan,
              nan])

In [82]:
np.arctan(numarray_radian)

array([0.2396503 , 0.50934978, 1.01863448, 0.83278096, 0.87780731,
       0.91194419])

In [83]:
numarray2 = np.array([31, 12, 87, 9, 61, 42])

In [84]:
numarray + numarray2

array([ 45,  44, 180,  72, 130, 116])

In [85]:
numarray*numarray2

array([ 434,  384, 8091,  567, 4209, 3108])

In [86]:
np.concatenate((numarray, numarray2))

array([14, 32, 93, 63, 69, 74, 31, 12, 87,  9, 61, 42])

In [87]:
numarray2d = np.array((numarray, numarray2))

In [181]:
numarray2d

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42]])

In [182]:
numarray2d + np.array([[1, 2]])

ValueError: operands could not be broadcast together with shapes (2,6) (1,2) 

In [89]:
numarray.ndim

1

In [90]:
numarray2.ndim

1

In [91]:
numarray2d.ndim

2

In [92]:
numarray.shape

(6,)

In [93]:
numarray2d.shape[1]

6

In [94]:
numarray2d[0,3]

63

In [95]:
numarray2d[1, 4]

61

In [96]:
numarray2d[0, 5]

74

In [97]:
numarray2d[0:2, 2:3]

array([[93],
       [87]])

In [98]:
numarray3 = np.array([[4, 1, 19, 22, 88, 34]])

In [99]:
a = np.concatenate((numarray2d, numarray3), axis = 0)

In [100]:
numarray3.ndim

2

In [101]:
numarray2d

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42]])

In [102]:
a

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42],
       [ 4,  1, 19, 22, 88, 34]])

In [103]:
numarray4 = np.array([[4, 1]])

In [104]:
np.concatenate((numarray2d, numarray4.T), axis = 1)

array([[14, 32, 93, 63, 69, 74,  4],
       [31, 12, 87,  9, 61, 42,  1]])

In [105]:
b = numarray.reshape(2, 3)

In [106]:
b

array([[14, 32, 93],
       [63, 69, 74]])

In [107]:
numarray3

array([[ 4,  1, 19, 22, 88, 34]])

In [108]:
numarray3.reshape(3, 2)

array([[ 4,  1],
       [19, 22],
       [88, 34]])

In [109]:
numarray3.reshape(6, 1)

array([[ 4],
       [ 1],
       [19],
       [22],
       [88],
       [34]])

In [110]:
numarray3.reshape(1, 6)

array([[ 4,  1, 19, 22, 88, 34]])

In [111]:
numarray3 = np.array([[4, 1, 19, 22, 88, 34]])
numarray3.reshape(3, -1)

array([[ 4,  1],
       [19, 22],
       [88, 34]])

In [112]:
# numarray3.reshape(4, -1)

In [113]:
numarray2d.reshape(3, -1)

array([[14, 32, 93, 63],
       [69, 74, 31, 12],
       [87,  9, 61, 42]])

In [114]:
numarray2d.reshape(5, -1)

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

In [115]:
numarray2d.max()

93

In [116]:
numarray2d.min()

9

In [117]:
numarray2d.mean()

48.916666666666664

In [118]:
numarray2d.std()

28.285621592761384

In [119]:
numarray2d.nunique()

AttributeError: 'numpy.ndarray' object has no attribute 'nunique'

In [120]:
np.max(numarray2d)

93

In [123]:
np.max(numarray2d, axis = 0) # Maximum value of each column

array([31, 32, 93, 63, 69, 74])

In [124]:
numarray2d

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42]])

In [125]:
np.max(numarray2d, axis = 1) # Maximum value of each row

array([93, 87])

In [126]:
np.where(numarray == 93)

(array([2]),)

In [127]:
np.where(numarray2d == 93)

(array([0]), array([2]))

In [128]:
np.sort(numarray)

array([14, 32, 63, 69, 74, 93])

In [129]:
np.sort(numarray2d, axis = 0) # Sort the column 

array([[14, 12, 87,  9, 61, 42],
       [31, 32, 93, 63, 69, 74]])

In [130]:
np.sort(numarray2d, axis = 1) # Sort the row

array([[14, 32, 63, 69, 74, 93],
       [ 9, 12, 31, 42, 61, 87]])

In [131]:
numarray[numarray > 50]

array([93, 63, 69, 74])

In [132]:
numarray2d[numarray2d > 50]

array([93, 63, 69, 74, 87, 61])

In [133]:
np.linspace(0, 2, 10) # (start, stop, num)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [183]:
linarray = np.linspace(1, 6, 10)
linarray[4]

3.2222222222222223

In [135]:
np.arange(0, 10, 2) # (start, stop, step)

array([0, 2, 4, 6, 8])

In [136]:
np.arange(4, 20, 3)

array([ 4,  7, 10, 13, 16, 19])

In [137]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [138]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [139]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [143]:
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [155]:
numarray5 = np.array([[1, 2, 3, 4, 5, 6]])

In [156]:
numarray2d + numarray5

array([[15, 34, 96, 67, 74, 80],
       [32, 14, 90, 13, 66, 48]])

In [157]:
numarray5 = np.array([[1, 2]])

In [158]:
numarray2d + numarray5.T

array([[15, 33, 94, 64, 70, 75],
       [33, 14, 89, 11, 63, 44]])

In [159]:
numarray2d + numarray5

ValueError: operands could not be broadcast together with shapes (2,6) (1,2) 

In [160]:
numarray * numarray2 # Element by Element Multiplication

array([ 434,  384, 8091,  567, 4209, 3108])

In [161]:
np.dot(numarray, numarray2) # dot product of two 1d array(vectors)

16793

In [162]:
numarray@numarray2

16793

In [163]:
numarray2d

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42]])

In [164]:
numarray6 = np.array([2, 3])

In [168]:
np.matmul(numarray2d.T, numarray6)

array([121, 100, 447, 153, 321, 274])

In [169]:
np.dot(numarray2d.T, numarray6)

array([121, 100, 447, 153, 321, 274])

In [170]:
numarray2d.T@numarray6

array([121, 100, 447, 153, 321, 274])

In [171]:
numarray2d.T*numarray6

array([[ 28,  93],
       [ 64,  36],
       [186, 261],
       [126,  27],
       [138, 183],
       [148, 126]])

In [172]:
np.ndarray.flatten(numarray2d)

array([14, 32, 93, 63, 69, 74, 31, 12, 87,  9, 61, 42])

In [173]:
numarray2d.reshape(1, -1)

array([[14, 32, 93, 63, 69, 74, 31, 12, 87,  9, 61, 42]])

In [174]:
numarray2d.reshape(1, -6)#why ?

array([[14, 32, 93, 63, 69, 74, 31, 12, 87,  9, 61, 42]])

In [175]:
numarray2d.reshape(-1, 1)

array([[14],
       [32],
       [93],
       [63],
       [69],
       [74],
       [31],
       [12],
       [87],
       [ 9],
       [61],
       [42]])

In [176]:
numarray2d.reshape(1, 1)

ValueError: cannot reshape array of size 12 into shape (1,1)

In [177]:
np.random.rand(6) #Randomly chosen from the interval (0, 1)

array([0.32407909, 0.64093355, 0.87269144, 0.47847271, 0.25619524,
       0.56199837])

In [178]:
np.random.rand(2, 4)

array([[0.974993  , 0.5238114 , 0.59599502, 0.8792438 ],
       [0.69371961, 0.29389861, 0.65703759, 0.93684657]])

In [179]:
np.random.randint(3, 10, 7)

array([4, 4, 7, 8, 8, 7, 4])

In [180]:
np.random.randint(3, 10, (2, 4))

array([[6, 4, 5, 8],
       [9, 3, 3, 5]])

In [184]:
n1 = np.array([[14, 32, 45], [31, 12, 56]])

In [187]:
n2 = np.array([[63, 9], [93, 74]])

In [188]:
n1.T

array([[14, 31],
       [32, 12],
       [45, 56]])

In [186]:
n1.T@n2

array([[3765, 2420],
       [3132, 1176],
       [8043, 4549]])

In [191]:
numarray2d

array([[14, 32, 93, 63, 69, 74],
       [31, 12, 87,  9, 61, 42]])

In [190]:
numarray2d[numarray2d > 50]

array([93, 63, 69, 74, 87, 61])

In [192]:
numarray@2

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)